apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: loja-virtual
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "springboot-logs"
      }
      stdout { codec => rubydebug }
    }
