apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: loja-virtual
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
