## YAML Template.
---
spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://mysql:3306/shopeasy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    consumer:
      group-id: shopeasy-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.shopeasy.ecommerce.kafka.dto
        session.timeout.ms: 15000
        heartbeat.interval.ms: 3000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false
      concurrency: 1
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

jwt:
  secret: minhaChaveSuperSecreta32Chars!123456
  access-token-expiration-ms: 86400000
  refresh-token-expiration-ms: 604800000

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
